const Personas = [
  {
    "id":"1",
    "nombre":"Sinclair",
    "apellido":"Stratley",
    "email":"sstratley0@ocn.ne.jp",
    "edad":"48"
  },
  {
    "id":"2",
    "nombre":"Kristi",
    "apellido":"Sloyan",
    "email":"ksloyan1@scientificamerican.com",
    "edad":"42"
  },
  {
    "id":"3",
    "nombre":"Marsiella",
    "apellido":"Ferronier",
    "email":"mferronier2@shareasale.com",
    "edad":"40"
  },
  {
    "id":"4",
    "nombre":"Gunter",
    "apellido":"Huson",
    "email":"ghuson3@gmpg.org",
    "edad":"54"
  },
  {
    "id":"5",
    "nombre":"Burl",
    "apellido":"Iveson",
    "email":"biveson4@ted.com",
    "edad":"59"
  },
  {
    "id":"6",
    "nombre":"Neysa",
    "apellido":"Leveridge",
    "email":"nleveridge5@gmpg.org",
    "edad":"39"
  },
  {
    "id":"7",
    "nombre":"Dan",
    "apellido":"Sporner",
    "email":"dsporner6@gnu.org",
    "edad":"65"
  },
  {
    "id":"8",
    "nombre":"Dinny",
    "apellido":"Comford",
    "email":"dcomford7@huffingtonpost.com",
    "edad":"41"
  },
  {
    "id":"9",
    "nombre":"Thelma",
    "apellido":"Elintune",
    "email":"telintune8@house.gov",
    "edad":"58"
  },
  {
    "id":"10",
    "nombre":"Jewelle",
    "apellido":"Shoosmith",
    "email":"jshoosmith9@themeforest.net",
    "edad":"35"
  },
  {
    "id":"11",
    "nombre":"Elyn",
    "apellido":"Dunkley",
    "email":"edunkleya@moonfruit.com",
    "edad":"25"
  },
  {
    "id":"12",
    "nombre":"Moishe",
    "apellido":"Winspare",
    "email":"mwinspareb@webeden.co.uk",
    "edad":"59"
  },
  {
    "id":"13",
    "nombre":"Gilbertine",
    "apellido":"Teale",
    "email":"gtealec@github.com",
    "edad":"58"
  },
  {
    "id":"14",
    "nombre":"Harris",
    "apellido":"Beels",
    "email":"hbeelsd@virginia.edu",
    "edad":"27"
  },
  {
    "id":"15",
    "nombre":"Malchy",
    "apellido":"Danilovitch",
    "email":"mdanilovitche@theatlantic.com",
    "edad":"25"
  },
  {
    "id":"16",
    "nombre":"Bevvy",
    "apellido":"Shitliff",
    "email":"bshitlifff@prnewswire.com",
    "edad":"52"
  },
  {
    "id":"17",
    "nombre":"Alyce",
    "apellido":"Maceur",
    "email":"amaceurg@sphinn.com",
    "edad":"24"
  },
  {
    "id":"18",
    "nombre":"Dex",
    "apellido":"McCurley",
    "email":"dmccurleyh@nps.gov",
    "edad":"61"
  },
  {
    "id":"19",
    "nombre":"Derry",
    "apellido":"Currer",
    "email":"dcurreri@so-net.ne.jp",
    "ed ad":"44"
  },
  {
    "id":"20",
    "nombre":"Eldon",
    "apellido":"McWard",
    "email":"emcwardj@washington.edu",
    "edad":"37"
  },
  {
    "id":"21",
    "nombre":"Celestine",
    "apellido":"Folca",
    "email":"cfolcak@java.com",
    "edad":"50"
  },
  {
    "id":"22",
    "nombre":"Skylar",
    "apellido":"Farmiloe",
    "email":"sfarmiloel@dropbox.com",
    "edad":"25"
  },
  {
    "id":"23",
    "nombre":"Nola",
    "apellido":"Droghan",
    "email":"ndroghanm@narod.ru",
    "edad":"54"
  },
  {
    "id":"24",
    "nombre":"Clevie",
    "apellido":"Haisell",
    "email":"chaiselln@spiegel.de",
    "edad":"37"
  },
  {
    "id":"25",
    "nombre":"Jenine",
    "apellido":"Cottey",
    "email":"jcotteyo@nymag.com",
    "edad":"35"
  },
  {
    "id":"26",
    "nombre":"Loraine",
    "apellido":"Frenchum",
    "email":"lfrenchump@chron.com",
    "edad":"53"
  },
  {
    "id":"27",
    "nombre":"Joann",
    "apellido":"Moquin",
    "email":"jmoquinq@fotki.com",
    "edad":"43"
  },
  {
    "id":"28",
    "nombre":"Rock",
    "apellido":"Crowhurst",
    "email":"rcrowhurstr@usa.gov",
    "edad":"38"
  },
  {
    "id":"29",
    "nombre":"Curtice",
    "apellido":"Owbrick",
    "email":"cowbricks@about.me",
    "edad":"54"
  },
  {
    "id":"30",
    "nombre":"Donovan",
    "apellido":"Corradengo",
    "email":"dcorradengot@cargocollective.com",
    "edad":"45"
  },
  {
    "id":"31",
    "nombre":"Burke",
    "apellido":"Sysland",
    "email":"bsyslandu@google.com",
    "edad":"57"
  },
  {
    "id":"32",
    "nombre":"Deina",
    "apellido":"Ridges",
    "email":"dridgesv@prweb.com",
    "edad":"21"
  },
  {
    "id":"33",
    "nombre":"Wynne",
    "apellido":"Turbill",
    "email":"wturbillw@mozilla.com",
    "edad":"53"
  },
  {
    "id":"34",
    "nombre":"Mandel",
    "apellido":"Whenham",
    "email":"mwhenhamx@jigsy.com",
    "edad":"40"
  },
  {
    "id":"35",
    "nombre":"Christie",
    "apellido":"Tranfield",
    "email":"ctranfieldy@linkedin.com",
    "edad":"43"
  },
  {
    "id":"36",
    "nombre":"Ephrayim",
    "apellido":"Bocken",
    "email":"ebockenz@quantcast.com",
    "edad":"58"
  },
  {
    "id":"37",
    "nombre":"Delia",
    "apellido":"MacNair",
    "email":"dmacnair10@fastcompany.com",
    "edad":"34"
  },
  {
    "id":"38",
    "nombre":"Archie",
    "apellido":"Fitzharris",
    "email":"afitzharris11@arstechnica.com",
    "edad":"35"
  },
  {
    "id":"39",
    "nombre":"Tibold",
    "apellido":"Yelden",
    "email":"tyelden12@thetimes.co.uk",
    "edad":  "31"  
  },
  {
    "id":"40",
    "nombre":"Lazarus",
    "apellido":"Pimerick",
    "email":"lpimerick13@theglobeandmail.com",
    "edad":"63"
  },
  {
    "id":"41",
    "nombre":"Herman",
    "apellido":"MacElholm",
    "email":"hmacelholm14@usgs.gov",
    "edad":"35"
  },
  {
    "id":"42",
    "nombre":"Harry",
    "apellido":"Ritchley",
    "email":"hritchley15@fastcompany.com",
    "edad":"30"
  },
  {
    "id":"43",
    "nombre":"Ebenezer",
    "apellido":"Billsberry",
    "email":"ebillsberry16@hatena.ne.jp",
    "edad":  "43"  
  },
  {
    "id":"44",
    "nombre":"Harlin",
    "apellido":"Hehl",
    "email":"hhehl17@wunderground.com",
    "edad":"60"
  },
  {
    "id":"45",
    "nombre":"Barbara",
    "apellido":"Rubinov",
    "email":"brubinov18@com.com",
    "edad":"25"
  },
  {
    "id":"46",
    "nombre":"Claudian",
    "apellido":"Klageman",
    "email":"cklageman19@hubpages.com",
    "edad":"24"
  },
  {
    "id":"47",
    "nombre":"Annadiana",
    "apellido":"Maior",
    "email":"amaior1a@wordpress.com",
    "edad":"61"
  },
  {
    "id":"48",
    "nombre":"Federico",
    "apellido":"Ratnege",
    "email":"fratnege1b@upenn.edu",
    "edad":"40"
  },
  {
    "id":"49",
    "nombre":"Sib",
    "apellido":"Brumfield",
    "email":"sbrumfield1c@sina.com.cn",
    "edad":  "58"  
  },
  {
    "id":"50",
    "nombre":"Neila",
    "apellido":"Greensall",
    "email":"ngreensall1d@multiply.com",
    "edad":"28"
  },
  {
    "id":"51",
    "nombre":"Wilburt",
    "apellido":"Barroux",
    "email":"wbarroux1e@prlog.org",
    "edad":"47"
  },
  {
    "id":"52",
    "nombre":"Delinda",
    "apellido":"Chaffer",
    "email":"dchaffer1f@imageshack.us",
    "edad":"55"
  },
  {
    "id":"53",
    "nombre":"Gerladina",
    "apellido":"McGonagle",
    "email":"gmcgonagle1g@squarespace.com",
    "edad":"28"
  },
  {
    "id":"54",
    "nombre":"Salomon",
    "apellido":"Kellie",
    "email":"skellie1h@tinyurl.com",
    "edad":"36"
  },
  {
    "id":"55",
    "nombre":"Yale",
    "apellido":"Benthall",
    "email":"ybenthall1i@symantec.com",
    "edad":"34"
  },
  {
    "id":"56",
    "nombre":"Moll",
    "apellido":"Riddlesden",
    "email":"mriddlesden1j@shinystat.com",
    "edad":"19"
  },
  {
    "id":"57",
    "nombre":"Denny",
    "apellido":"Rittmeier",
    "email":"drittmeier1k@nba.com",
    "edad":"59"
  },
  {
    "id":"58",
    "nombre":"Logan",
    "apellido":"Lamport",
    "email":"llamport1l@hibu.com",
    "edad":"29"
  },
  {
    "id":"59",
    "nombre":"Vassili",
    "apellido":"Abbison",
    "email":"vabbison1m@nbcnews.com",
    "edad":"32"
  },
  {
    "id":"60",
    "nombre":"Roth",
    "apellido":"Kilmary",
    "email":"rkilmary1n@businessinsider.com",
    "edad":"48"
  },
];

export default Personas